site:
    title: PieCrust Demo
    template_engine: Dwoo
    pretty_urls: true

markdown:
    use_markdown_extra: true
    use_smartypants: true

smartypants:
    enable: true
    use_smartypants_typographer: true
