site:
    title: PieCrust Demo
    enable_cache: false
    enable_gzip: true
    pretty_urls: true
    debug: true
    posts_per_page: 3

markdown:
    use_markdown_extra: true

smartypants:
    enable: true
    use_smartypants_typographer: true
